server:
  port: 8080

grpc:
  server:
    port: 59091

collector:
  kafka:
    configuration:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": telemetry.collector
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.serialization.GeneralAvroSerializer
      topics:
        sensor: telemetry.sensors.v1
        hub: telemetry.hubs.v1
