server:
  port: 0

spring:
  application:
    name: shopping-store

  datasource:
    url: jdbc:postgresql://localhost:5433/shopping_store
    username: main
    password: main
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      jdbc.time_zone: UTC

  sql:
    init:
      mode: always

  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.hibernate.SQL: DEBUG